config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  resources :users, only: [:new, :create]

  get "login", to: "sessions#new"
  get "admin", to: "sessions#admin"
  get "logout", to: "sessions#logout"
  post "login", to: "sessions#create"

  get "bulletin", to: "generators#bulletin", as: "bulletin"

  resources :projects
  resources :generators

  root "generators#index"
end

app/models/project.rb
# frozen_string_literal: true

class Project < ApplicationRecord
  belongs_to :generator
  validates :name, :label, presence: true
end

app/controllers/projects_controller.rb
# frozen_string_literal: true

class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to projects_url, notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to projects_url, notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :label, :code, :prefix, :suffix, :generator_id)
    end
end

app/helpers/projects_helper.rb
# frozen_string_literal: true

module ProjectsHelper
end

app/views/projects/_form.html.erb
  <div class="row">
    <div class="col">
      <%= form_with(model: project, local: true) do |form| %>
      <% if project.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(project.errors.count, "error") %> 
            prohibited this project from being saved:
          </h2>
          <ul>
          <% project.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
      <% end %>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <%= simple_form_for(@project) do |f| %>
        <%= f.input :name, as: :string, label: "Project Name", required: true %>
        <%= f.input :code, as: :string, label: "Repository Code" %>
        <%= f.input :label, as: :string, label: "Project Label", required: true %>
        <%= f.association :generator %>

        <%= f.button :submit, class: "btn btn-secondary" %>
      <% end %>
    </div>
  </div>

app/views/projects/edit.html.erb
  <h1>Editing Project</h1>

  <%= render 'form', project: @project %>

  <div class="actions mt-3">
    <%= link_to 'Show', @project %> |
    <%= link_to 'Back', projects_path %>
  </div>

app/views/projects/index.html.erb
<div class="row">
  <div class="col">
    <h1>Projects</h1>
  </div>
</div>

<div class="row">
  <div class="col mt2">
    <p><%= link_to 'Create New Project', new_project_path, class: "new-project" %></p>
  </div>
</div>

<div class="row">
  <div class="col">
    <table border="0" width="100%" style="border-top: 0">
      <thead>
        <tr>
          <th width="35%">Project Name</th>
          <th>Repository Code</th>
          <th>Project Label</th>
          <th>Generator</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @projects.order(:name).each do |project| %>
          <tr>
            <td><%= project.name %></td>
            <td><%= project.code %></td>
            <td><%= project.label %></td>
            <td><%= link_to project.generator.name, generator_path(project.generator) %></td>
            <td><%= link_to 'Show', project %></td>
            <td><%= link_to 'Edit', edit_project_path(project) %></td>
            <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<div class="row">
  <div class="col mt-5 mb-5">
    <%= link_to 'Create New Project', new_project_path, class: "new-project" %>
  </div>
</div>

app/views/projects/new.html.erb
	<h1>New Project</h1>

	<%= render 'form', project: @project %>

	<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<div class="row mb-2">
  <h1>Project</h1>
</div>

<div class="row mb-2">
  <div class="col">
    <strong>Name: </strong> 
    <%= @project.name %>
  </div>
</div>

<div class="row mb-2">
  <div class="col">
    <strong>Repository Code:</strong> 
    <%= @project.code %>
  </div>
</div>

<div class="row mb-2">
  <div class="col">
    <strong>label:</strong> 
    <%= @project.label %>
  </div>
</div>

<div class="row mb-2">
  <div class="col">
    <strong>generator:</strong> 
    <%= link_to @project.generator.name, generator_path(@project.generator) %>
  </div>
</div>

<div class="row mt-3" >
  <div class="col">
    <%= link_to 'Edit', edit_project_path(@project) %> |
    <%= link_to 'Back', projects_path %>
  </div>
</div>