config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  resources :users, only: [:new, :create]

  get "login", to: "sessions#new"
  get "admin", to: "sessions#admin"
  get "logout", to: "sessions#logout"
  post "login", to: "sessions#create"

  get "bulletin", to: "generators#bulletin", as: "bulletin"

  resources :projects
  resources :generators

  root "generators#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NoidGenerators</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbo-track': 'reload' %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <div class="header container">
      <div class="row" id="header">
        <div class="col col-10">
          <h1>Special Collections Research Center</h1>
        </div>
        <div class="col col-2">
          <div class="dropdown">
            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenu2" data-bs-toggle="dropdown" data-bs-target="#dropdown-menu" aria-haspopup="true" aria-expanded="false">
              Menu
            </button>

            <div id="dropdown-menu" class="dropdown-menu" aria-labelledby="dropdownMenu2">
              <% if logged_in? %>
                <% unless bulletin_user? %>
                <%= link_to "Generators", generators_path, class: "dropdown-item btn btn-secondary" %>
                <% if is_admin? %>
                  <%= link_to "Projects", projects_path, class: "dropdown-item btn btn-secondary" %>
                <% end %>
                <div class="dropdown-divider"></div>
                <% end %>
                <%= link_to "Logout", '/logout', class: "dropdown-item btn btn-secondary" %>
              <% else %>
                <%= form_tag(login_path, {class: "p-4"}) do %>   
                  <%= label_tag :username %>   
                  <%= text_field_tag :username %>   
                  <%= label_tag :password %>   
                  <%= password_field_tag :password %>   
                  <%= submit_tag "Login", class: "btn btn-secondary", style: "margin-top: 10px" %>
                <%end%>
              <% end %>
            </div>
          </div>
        </div>
      </div>
      <% if notice.present? %>
        <div class="row">
          <div class="col text-center">
            <p id="notice" class="h2"><%= notice %></p>
          </div>
        </div>
      <% end %>

      <div class="yield container">

        <%= yield %>

      </div>
    
    </div>  
  </body>
</html>